### ISSUE TITLE
InvalidLicenseMessage: Cannot parse an empty license_message

### ISSUE THREAD

**Issue by Abhi5033** [glomatico/spotify-web-downloader#16]
I'm getting this error

![image](https://github.com/glomatico/spotify-aac-downloader/assets/118114270/56f1a709-68d4-4115-a467-60e5818d5a67)

1. Using latest version of ffmpeg from https://github.com/AnimMouse/ffmpeg-stable-autobuild/releases
2. wvd file is in location (working for gamdl apple music downloader) 
3. Spotify premium account cookies

**Comment by herrcaleb** [comment]
Hello,
I didnt want to open a seperate issue because I ran into this error too.
It happens when I am downloading from a -r *.txt file and happens randomly after 50-100 songs. If I restart the program it works again until a few songs but then this error occurs again.
Whats the matter?
Thanks!
