### ISSUE TITLE
Paralell downloads

### ISSUE THREAD

**Issue by felipemarinho97** [glomatico/spotify-web-downloader#22]
It is possible to download the songs in parallel? Downloading a playlist with 800 songs is taken forever because its being done sequentially. Im using aria2c, but this did'nt help.

If not, how hard is to add this feature?

**Comment by Fawn77** [comment]
I dont think parallel download is eligible for requesting the web many times. Thats why playlist download exists, its more "humanized" coz its requesting the apis each time the download finished, and repeat. 

Also, Spotify will block your IPs after several times. Im not counting it, but I feel after more than 50 requests -> blocked IPs. Coz "raping" the APIs many times is considered as bot. 

So playlist download is the best option. If you wanna download all 800 songs, separate it into 8 or 10 playlists where each playlist contains 100 songs. 

And download one by one playlist each 1 or 2 hours. I dont really remember whats the total time Spotify unblock the IPs. Maybe 1 or 2 hours, or maybe up to 3 hours.

**Comment by felipemarinho97** [comment]
@Fawn77 you are right, thank you!
