### ISSUE TITLE
Can't download next track 

### ISSUE THREAD

**Issue by Droidman007** [glomatico/spotify-web-downloader#24]
~ $ spotify-web-downloader https://open.spotify.com/album/3EkmvTqyKrnMw1WiVpsSwF?si=z9HUKMkLSGGFSD9018yahQ&context=spotify%3Aalbum%3A3EkmvTqyKrnMw1WiVpsSwF
[4] 6135
~ $ [INFO     09:24:38] (Track 1/6 from URL 1/1) Downloading "Galliyan"

[4]+  Stopped                 spotify-web-downloader https://open.spotify.com/album/3EkmvTqyKrnMw1WiVpsSwF?si=z9HUKMkLSGGFSD9018yahQ

~ $ ls temp/                                                               3ySVdXje5nm31d7vL3jNV3_encrypted.m4a                                       ~ $

I am using this in termux after downloading on track it can not download the other one in the album

**Comment by glomatico** [comment]
Put your link under quote
