### ISSUE TITLE
InvalidLicenseMessage: Cannot parse an empty license_message

### ISSUE THREAD

**Issue by belacrreh** [glomatico/spotify-web-downloader#30]
Hello,
https://github.com/glomatico/spotify-web-downloader/issues/16
![294229254-56f1a709-68d4-4115-a467-60e5818d5a67](https://github.com/glomatico/spotify-web-downloader/assets/105661616/689b7244-4833-40d9-aab2-21461e9fec96)
I didnt want to open a seperate issue but apparently have to because I ran into this error too.
It happens when I am downloading from a -r *.txt file and happens randomly after 50-100 songs. If I restart the program it works again until a few songs but then this error occurs again.
Whats the matter?
Thanks!

**Comment by glomatico** [comment]
There's nothing you can do besides waiting. Spotify throttles if you download too much songs in a short period of the time.

**Comment by belacrreh** [comment]
Ah I thought about that issue. Yeah theres nothing we cant do sadly. I actually updated to the latest version but I just copy pasted the image from the other issue to leave me some hassle since they are both the same error issue. Thank you though for your program!
