### ISSUE TITLE
cookies.txt not found 

### ISSUE THREAD

**Issue by Vinc137** [glomatico/spotify-web-downloader#34]
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.txt'FileNotFoundError: [Errno 2] No such file or directory: 'cookies.txt'
i did as you said and i get this error 
plzs help me

**Comment by glomatico** [comment]
You did not placed the cookies on the same directory

**Comment by Vinc137** [comment]
but i did

**Comment by glomatico** [comment]
No, you did not. Place it on the current directory or specify the path using cookies path option.

**Comment by Vinc137** [comment]
How do I do that?
