### ISSUE TITLE
The syntax of the USAGE in the README is incorrect

### ISSUE THREAD

**Issue by rDamascena** [glomatico/spotify-web-downloader#40]
The syntax of the [USAGE](https://github.com/glomatico/spotify-web-downloader#usage) in the README is incorrect:

`spotify_web_downloader [OPTIONS] URLS...`

Suggestion:

Replace `spotify_web_downloader` [OPTIONS] URLS... with `spotify-web-downloader` [OPTIONS] URLS...

**Comment by glomatico** [comment]
Okay.
