### ISSUE TITLE
It says that there's no cookies file, but there's one actually

### ISSUE THREAD

**Issue by sergiohzph** [glomatico/spotify-web-downloader#41]
![image](https://github.com/glomatico/spotify-web-downloader/assets/138529583/1c6c4b8e-e3b3-44dc-91c6-d74889c706ff)
What is happening? I just placed the cookies file inside the app's directory as you stated in the readme.

**Comment by glomatico** [comment]
Not inside the script folder, you should put the cookies on the current directory of your terminal. If you are still confused, just use the command `explorer .` and move the cookies to the folder that opened.

**Comment by sergiohzph** [comment]
Alright thanks, it works now. I've a question, is this bannable? Is there any risk if I download too many songs at once? Or is it just like as I was downloading the songs inside the app? I'm a Premium user so I guess it won't be dangerous for me, but I just want to make sure.

**Comment by glomatico** [comment]
You should be ok, but Spotify may throttle if you download too many songs.
