### ISSUE TITLE
Position of songs in a playlist

### ISSUE THREAD

**Issue by AlexPaterson77** [glomatico/spotify-web-downloader#49]
This script is really great, I just can not find a way to rename the downloaded songs using a number stating its position, when I download from an URL directing to a playlist.
It's a piece of data you should already have, as I see strings like  "(Track **1**/22 from URL 1/1)", "(Track **2**/22 from URL 1/1)" being prompted when the scripts executes the download. 
Though, when using the track tag, it refers to its position in the album it originally comes from, not the position in the playlist.

**Comment by SeriousM** [comment]
One way to work around that issue is to just download the files, then sort them by creation date and change the names yourself. I know, that's tedious but that's what a workaround is. Just make sure to add some download delay, otherwise you will end up with missing pieces.

**Comment by AlexPaterson77** [comment]
I actually added the following line to the cli.py file

tags["index"] = str(queue_index).zfill(2);

In the main method, line 469.
This way i have a new tag called index, i can use in the configuration file as a naming convention for files.

**Comment by glomatico** [comment]
The new playlist tags and save playlist option on version 1.8 should address this issue.
