### ISSUE TITLE
Lot of 400 Bad requets

### ISSUE THREAD

**Issue by vijaykrpp** [glomatico/spotify-web-downloader#58]
Hi,

I have been using it for 3 months now. Suddenly, I encounter a lot of Request failed with status code 400: {\"error\": {\"status\": 400, \"message\": \"Bad Request\"  errors.

I tried changing cookies of different Spotify a/c from paid one to free one, changing servers, but nothing changed.

**Comment by glomatico** [comment]
Spotify is known for throttling when you download too many songs. Try waiting a few hours and days.

**Comment by vijaykrpp** [comment]
Hi,

Apologies. It was not a  client-side issue. Spotify API was down for 3 hours yesterday. Everything is OK now and I forgot to close this issue.

Usually, when you do too many requests, they throw 429 but this time theu threw 400 which was new to me.
