### ISSUE TITLE
FFMPEG not found

### ISSUE THREAD

**Issue by JeremieGuy** [glomatico/spotify-web-downloader#63]
Issue : ffmpeg not found when trying to download a track

Steps : 
- install script
- create cookies.txt in correct directoy using _open Cookies.txt_ extention from chrome browser
- try downloading track using simple exec command with no additionnal options

Error : 
[CRITICAL 15:44:33] ffmpeg not found at ffmpeg

Did I miss anything in the install/cookie file ? I created the cookies file directly from the spotify website when logged in with my account using the chrome extension. Same issue for different tracks. Thx in advance for your help.

**Comment by glomatico** [comment]
You have to add FFmpeg to PATH and be able to run the command `ffmpeg` without problems.
