### ISSUE TITLE
[CRITICAL] All requests 403 errors since last 5 hours

### ISSUE THREAD

**Issue by vijaykrpp** [glomatico/spotify-web-downloader#66]
Hi,

All the requests giving 403 Forbidden errors. Checked the request and response headers, not much info why requests being denied. Tried changing cookies, server address, etc. 

![image](https://github.com/user-attachments/assets/58278bd4-8f76-42ad-b2d2-84e3cff91d1e)

P.S: I need to get it resolved fast. I am ready to pay you fee for that, Contact me on Twitter or Telegram:  vijaykrpp

**Comment by jacob-cooke** [comment]
fails at downloader_song.get_decryption_key
while trying to get a license using the spotify_api.get_widevine_license_music()

**Comment by glomatico** [comment]
Should be fixed on the newest version.
