### ISSUE TITLE
Banned (Reduce download speed?)

### ISSUE THREAD

**Issue by alany08** [glomatico/spotify-web-downloader#69]
I was using a burner account to download a playlist, but began encountering errors, and after rerunning the command a few times spotify started returning 401. Checking the web UI, the account has been banned.

**Comment by youngoris** [comment]
that's not good, thanks for sharing this.

**Comment by youngoris** [comment]
> I was using a burner account to download a playlist, but began encountering errors, and after rerunning the command a few times spotify started returning 401. Checking the web UI, the account has been banned.

Does your burner account have a premium subscription?

**Comment by alany08** [comment]
No, adding an artificial delay fixed this problem (although downloaded a lot slower)

**Comment by glomatico** [comment]
The newest version now includes the option `wait_interval` that adds intervals between downloads in seconds, and it should help with throttling.
