### ISSUE TITLE
error downloading

### ISSUE THREAD

**Issue by phwaleed2024** [glomatico/spotify-web-downloader#72]

**Comment by glomatico** [comment]
Please provide more details.

**Comment by phwaleed2024** [comment]
![Screenshot (2)](https://github.com/user-attachments/assets/141d9bd3-7fc0-4378-8b50-ba5c93200d13)

**Comment by glomatico** [comment]
Run the same command again but with `--print-exceptions` at the end.

**Comment by phwaleed2024** [comment]
![Screenshot (3)](https://github.com/user-attachments/assets/9680027d-05cf-450b-b005-8dfc0498a8c9)
![Screenshot (4)](https://github.com/user-attachments/assets/f9212078-cf26-44b9-bdf6-58bc86961a4b)

**Comment by phwaleed2024** [comment]
it was working ok until last week since i opened the new case

**Comment by glomatico** [comment]
You have to update to the latest version by running `pip install -U spotify-web-downloader`.

**Comment by phwaleed2024** [comment]
it worked now perefectly 
thanks alot
