### ISSUE TITLE
Spotify Widevine License API Update

### ISSUE THREAD

**Issue by alany08** [glomatico/spotify-web-downloader#74]
1. The URL base has been updated to https://guc3-spclient.spotify.com/
2. A new cookie has appeared, called `client-token`. All requests from spotify-web-downloader now fail with a 403

**Comment by pdtan** [comment]
Maybe you used old hardcoded_wvd, update it to newest version.
Old url and cookie without client-token are working fine.

**Comment by glomatico** [comment]
can confirm that it's still working. make sure to update to the latest version with pip:
```
pip install -U spotify-web-downloader
```
