### ISSUE TITLE
fail again in download

### ISSUE THREAD

**Issue by phwaleed2024** [glomatico/spotify-web-downloader#78]
i got error again in downloading any song
[
![Screenshot (7)](https://github.com/user-attachments/assets/e6ee49fb-4669-42d8-813b-883a92f720d8)
](url)

**Comment by glomatico** [comment]
Duplicate of #70

**Comment by phwaleed2024** [comment]
i made the update as the last time but still fails

**Comment by phwaleed2024** [comment]
i run that
pip install -U spotify-web-downloader
but the same error i get
