### ISSUE TITLE
download fail

### ISSUE THREAD

**Issue by phwaleed2024** [glomatico/spotify-web-downloader#79]
sir i did what you said before :
pip install -U spotify-web-downloader
but i still get that error
before it worked since you closed the case but now it again give me that error since 2 days
![Screenshot (7)](https://github.com/user-attachments/assets/6e01f9e9-3740-4eef-a683-3ac610413940)

**Comment by phwaleed2024** [comment]
after i downloaded your update since 50 minutes ago and set that fommand :
 pip install -U spotify-web-downloader
i got that error
![Uploading Screenshot (8).png…]()

**Comment by phwaleed2024** [comment]
i put a device.wvd file in the same directory as you see and i still get the same error
![Screenshot (9)](https://github.com/user-attachments/assets/6dcca888-3fd4-4dd7-9f1d-392daddbe9a3)

**Comment by glomatico** [comment]
Try from a different device.
